services:
  # payara service
  payara:
      container_name: payara-ws
      image: payara/server-full:6.2025.8-jdk17
      environment:
          SECURE_ADMIN: "true"
          ADMIN_USER: "admin"
          ADMIN_PASSWORD: "admin"
      ports:
        - "8080:8080" # apps
        - "4848:4848" # admin console
      volumes:
          # auto deploy (
       - ./Bookit-webservice/target/Bookit-webservice-1.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/Bookit-webservice-1.0-SNAPSHOT.war

          # translate http requests into java